name: my_weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #firebase dependencies
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.15.8

  firebase_messaging:

  http: ^1.2.0  #for fetching data from api
  location: ^4.3.0 #fetch location of user
  shared_preferences: ^2.0.5 #store data locally

  flutter_bloc: ^8.0.0  #add bloc state-management
  intl: ^0.19.0


  equatable:
  flutter_local_notifications: ^17.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/poppins/
    - assets/images/world_map_bg.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

